export default {
  products: [
    {
      id: '1',
      catagory: 'Shirt',
      name: 'Slim Shirt',
      image: '/images/shirt1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: '2',
      catagory: 'Shirt',
      name: 'Fit Shirt',
      image: '/images/shirt1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: '3',
      catagory: 'Pant',
      name: 'Jeans 01',
      image: '/images/shirt1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: '4',
      catagory: 'Pant',
      name: 'Jeans 02',
      image: '/images/shirt1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: '5',
      catagory: 'Pant',
      name: 'Jeans 02',
      image: '/images/shirt1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
    {
      id: '6',
      catagory: 'Pant',
      name: 'Jeans 02',
      image: '/images/shirt1.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
    },
  ],
};
